echo "WARNING: THIS SCRIPT CANNOT BE RUN AT THE SAME TIME AS ANYTHING RUNNING GST"
if [ $# -ne 3 ]; then
    echo "USAGE: bash $0 batch-file batch-autogenerated-pml-dir num-threads"
    exit
fi

BATCH_FILE=$1
AUTOGENERATED_PML_DIR=$2
NUM_THREADS=$3
BATCH_NAME=$( echo "${BATCH_FILE}" | rev | cut -d/ -f1 | rev | cut -d. -f1 )

SCRIPT_DIR=$( cd $( dirname $0 ) && pwd )
LOGS_DIR=${SCRIPT_DIR}/${BATCH_NAME}-logs
mkdir -p ${LOGS_DIR}
OVERALL=${LOGS_DIR}/gol-summary
WRAPPER_DIR=${SCRIPT_DIR}/data/${BATCH_NAME}-wrapper
WRAPPER_TGZ=${SCRIPT_DIR}/data/${BATCH_NAME}-wrapper.tgz

curr_date=`date +%Y-%m-%d-%H-%M-%S`
if [ -d "${WRAPPER_DIR}" ]; then
    echo "Batch directory exists! Not running..."
    exit
fi

if [ -f "${WRAPPER_TGZ}" ]; then
    echo "Archive exists! moving batch..."
    mv ${SCRIPT_DIR}/data/${BATCH_NAME}-wrapper.tgz ${SCRIPT_DIR}/data/${BATCH_NAME}-wrapper-${curr_date}.tgz
fi


echo "RUN FOR BATCH ${BATCH_NAME} STARTED AT: "`date +%Y-%m-%d-%H-%M-%S` | tee -a ${OVERALL}

for automata in $( cat ${BATCH_FILE} ); do
    echo =========${automata}
    fixed_automaton_name=$( echo "${automata}" | sed 's/\$//g' ) # if the original name of the automaton has a $, then the autogenerator has gotten rid of that $ sign
    ( time bash ${SCRIPT_DIR}/run-optimized-generalized-spec-testing.sh ${AUTOGENERATED_PML_DIR}/${fixed_automaton_name} ${NUM_THREADS} ) &> ${LOGS_DIR}/gol-run-${BATCH_NAME}-${automata}
done

echo "RUN FOR BATCH ${BATCH_NAME} ENDED AT: "`date +%Y-%m-%d-%H-%M-%S` | tee -a ${OVERALL}

echo "DONE RUNNING..."
echo "PROCESSING BATCH ${BATCH_NAME} STARTED AT: "`date +%Y-%m-%d-%H-%M-%S` | tee -a ${OVERALL}
bash ${SCRIPT_DIR}/process-generalized-spec-testing.sh
echo "PROCESSING BATCH ${BATCH_NAME} ENDED AT: "`date +%Y-%m-%d-%H-%M-%S` | tee -a ${OVERALL}

summary_file=${SCRIPT_DIR}/data/generated-data/summary-results.csv
new_summary_file=${WRAPPER_DIR}/generated-data/summary-results.csv

echo "MOVING FILES..."
mkdir -p ${WRAPPER_DIR}/generated-data
for automaton in $( cat ${BATCH_FILE} | grep -v ^$ ); do
    echo =========${automaton}
    fixed_automaton_name=$( echo "${automaton}" | sed 's/\$//g' ) # if the original name of the automaton has a $, then the autogenerator has gotten rid of that $ sign
    mv ${SCRIPT_DIR}/data/generated-data/${fixed_automaton_name} ${WRAPPER_DIR}/generated-data
done
cp ${summary_file} ${WRAPPER_DIR}/generated-data

mv ${LOGS_DIR} ${WRAPPER_DIR}
echo "PACKAGING..."
# FIXME: kinda hardcode-y
(
    cd ${SCRIPT_DIR}/data
    tar -czf ${BATCH_NAME}-wrapper.tgz ${BATCH_NAME}-wrapper
)
